### ISSUE TITLE
problem while building from github

### ISSUE THREAD

**Issue by quentinodigiminlabs** [drlukeparry/pycork#10]
Hi I tried to build pycork from the github using

``
git clone https://github.com/drlukeparry/pycork.git && cd ./pycork
git submodule update --init --recursive

python setup.py install
``

but I got the following error

``
In file included from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/cast.h:16,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/attr.h:13,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/quentin_digimind/pycork/python/pycork/module.cpp:9:
/home/quentin_digimind/pycork/external/pybind11/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
/home/quentin_digimind/pycork/external/pybind11/include/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  482 |             frame = frame->f_back;
      |                          ^~
In file included from /home/quentin_digimind/anaconda3/envs/PYSLM_ENV/include/python3.11/Python.h:42,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/detail/common.h:215,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/pytypes.h:12,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/cast.h:13,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/attr.h:13,
                 from /home/quentin_digimind/pycork/external/pybind11/include/pybind11/pybind11.h:13,
                 from /home/quentin_digimind/pycork/python/pycork/module.cpp:9:
/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
gmake[3]: *** [CMakeFiles/pycork.dir/build.make:76: CMakeFiles/pycork.dir/python/pycork/module.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:130: CMakeFiles/pycork.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/pycork.dir/rule] Error 2
gmake: *** [Makefile:182: pycork] Error 2
Traceback (most recent call last):
  File "/home/quentin_digimind/pycork/setup.py", line 77, in <module>
    setup(
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/pycork/setup.py", line 39, in run
    self.build_extension(ext)
  File "/home/quentin_digimind/pycork/setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', '--build', '.', '--target', ext.modName] + build_args, cwd=self.build_temp)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'pycork', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
``

Any idea on how to fix this ?

Thanks,

Quentin

**Comment by scorpion81** [comment]
The build errors seem to relate to changes in the PyFrame object in Python 3.11+ . You need to use atleast pybind 2.12 which contains fixes for those changes. In my pullrequest https://github.com/drlukeparry/pycork/pull/11 i just pointed the external pybind submodule to a newer version. So if you do a recursive git clone or update your submodules, and retrieve pybind 2.12 this way whilst using Python 3.11 or newer... this should do the trick.
