### ISSUE TITLE
unable to install pycork

### ISSUE THREAD

**Issue by antocaf99** [drlukeparry/pycork#6]
Hi, 
First of all thanks for the building this library, I am trying to use it for a project together with PythonSLM. Also I'm sorry but I'm very new to coding in general so this may be a stupid question.
When I try to install this library, both with pypi and by downloading the repository, I run into the same problem.
I am using MacOS M1 chip and I tried with both python 3.8 and python 3.10 on pycharm.
With python 3.8

`pip install pycork`

I get the response:
```
fatal error: 'gmp.h' file not found
          #include <gmp.h>
                   ^~~~~~~
      1 error generated.
      make[3]: *** [CMakeFiles/cork_static.dir/cork/isct/empty3d.cpp.o] Error 1
      make[3]: *** Waiting for unfinished jobs....
      make[2]: *** [CMakeFiles/cork_static.dir/all] Error 2
      make[1]: *** [CMakeFiles/pycork.dir/rule] Error 2
      make: *** [pycork] Error 2
```
even though `gmp` is already installed both with homebrew and pip.
I get the same error even if I try installing it with the other method you provided.

For what I understand, it can't find the header file but I have no idea how to solve this issue.
I would be very grateful if you could help me out in any way,
Thank you.

**Comment by drlukeparry** [comment]
Hi, 

Thank you for clearly providing information about providing the reported issue, which is most helpful. 

I can acknowledge that there is indeed an issue trying to install via pip install using a source archive. The main issue is that I use git submodules in the source, so these cannot be incoporated into the source stored on the PyPi repository. It is not a quick fix.

Therefore , you need to create the package manually, you have to clone (including submodules) github repo and run `python setup.py bdist_wheel`

Can you find where your homebrew library is installed?  On my system, the  gmp.h file is located here:

`/opt/homebrew/include/gmp.h`

I am not a Mac expert, but I believe homebrew can be installed in a different directory and there can be issues locating it. 

If you can provide more information when compiling, it can be helpful to identify this issue. If you run into trouble, I can provide MacM1 packages for you to use.

**Comment by antocaf99** [comment]
Thank you for the quick response,
Through the command `find /usr /opt -name "gmp.h"` I get 2 outputs actually: 
```
/opt/homebrew/include/gmp.h
/opt/homebrew/Cellar/gmp/6.2.1_1/include/gmp.h
```

**Comment by drlukeparry** [comment]
That is the same as my system, so it seems unusual it cannot be located. 

In the pycork main folder, can you remove the old build files by delete the `build` folder.  Then can you report the entire output (including error) after executing:

`python setup.py bdist_wheel `

**Comment by antocaf99** [comment]
These are the warnings and errors I get
```
ld: warning: -L path '/Users/antocaf/Desktop/progetto10/lib/python3.8/site-packages/lib/libgmp.dylib' is not a directory
ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: ignoring file /Users/antocaf/Desktop/progetto10/lib/python3.8/site-packages/lib/libgmp.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/Library/Developer/CommandLineTools/usr/bin/strip -x /Users/antocaf/Dropbox\ (Politecnico\ Di\ Torino\ Studenti)/Mac/Desktop/progetto10/pycork/build/lib.macosx-10.9-x86_64-3.8/pycork/pycork.cpython-38-darwin.so'
make[3]: *** [/Users/antocaf/Dropbox (Politecnico Di Torino Studenti)/Mac/Desktop/progetto10/pycork/build/lib.macosx-10.9-x86_64-3.8/pycork/pycork.cpython-38-darwin.so] Error 2
make[3]: *** Deleting file `/Users/antocaf/Dropbox (Politecnico Di Torino Studenti)/Mac/Desktop/progetto10/pycork/build/lib.macosx-10.9-x86_64-3.8/pycork/pycork.cpython-38-darwin.so'
make[2]: *** [CMakeFiles/pycork.dir/all] Error 2
make[1]: *** [CMakeFiles/pycork.dir/rule] Error 2
make: *** [pycork] Error 2
```
I don't know if my path having spaces (Dropbox part) is a problem too or not.

**Comment by drlukeparry** [comment]
From the line,

`/bin/sh: -c: line 0: syntax error near unexpected token `('`

 I would suggest that you try in a simpler folder in your home directory and see if you observe the same result. From experinece, compiler scripts tend to not like spaces or symbols in the folder/directory path.

**Comment by antocaf99** [comment]
Thank you very much! I was able to install it, the main problem was probably the space in the path, I made a new project in the home directory and I was able to install the package with 

```
git clone https://github.com/drlukeparry/pycork.git && cd ./pycork
git submodule update --init --recursive

python setup.py install
```

**Comment by quentinodigiminlabs** [comment]
Hi guys,
I tried to install it following the command in the previous post but it yields the following error message


  CMake Error at CMakeLists.txt:67 (find_package):
   By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "Eigen3", but
   CMake did not find one.

   Could not find a package configuration file provided by "Eigen3" (requested
   version 3.3) with any of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

    Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
    "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
    provides a separate development package or SDK, be sure it has been
    installed.


   -- Configuring incomplete, errors occurred!
   Traceback (most recent call last):
   File "/home/quentin_digimind/pycork/setup.py", line 77, in <module>
    setup(
    File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
     return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/core.py", 
  line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site- 
 packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/quentin_digimind/pycork/setup.py", line 39, in run
    self.build_extension(ext)
  File "/home/quentin_digimind/pycork/setup.py", line 71, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/quentin_digimind/pycork', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/quentin_digimind/pycork/build/lib.linux-x86_64-cpython-311/pycork/', '-DPYTHON_EXECUTABLE=/home/quentin_digimind/anaconda3/envs/PYSLM_ENV/bin/python3', '-DBUILD_PYTHON=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=.']' returned non-zero exit status 1.
``
